//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date_Time_Slot
    {
        public int Date_Time_Slot_ID { get; set; }
        public Nullable<int> Shift_ID { get; set; }
        public Nullable<int> Time_Slot_ID { get; set; }
        public Nullable<int> Date_ID { get; set; }
    
        public virtual Date Date { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Time_Slot Time_Slot { get; set; }
    }
}
