//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Instance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_Instance()
        {
            this.Job_Instance_Task = new HashSet<Job_Instance_Task>();
        }
    
        public int Job_Instance_ID { get; set; }
        public Nullable<int> Job_task_ID { get; set; }
        public Nullable<int> Shift_Branch_Employee_ID { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Instance_Task> Job_Instance_Task { get; set; }
        public virtual Job_task Job_task { get; set; }
        public virtual Shift_Branch_Employee Shift_Branch_Employee { get; set; }
    }
}
