//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OVSEntities5 : DbContext
    {
        public OVSEntities5()
            : base("name=OVSEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Cart_Line> Cart_Line { get; set; }
        public virtual DbSet<Cash_Register> Cash_Register { get; set; }
        public virtual DbSet<Colour> Colours { get; set; }
        public virtual DbSet<Credit_Note> Credit_Note { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Type> Customer_Type { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<Date_Time_Slot> Date_Time_Slot { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Job_Instance> Job_Instance { get; set; }
        public virtual DbSet<Job_Instance_Task> Job_Instance_Task { get; set; }
        public virtual DbSet<Job_Status> Job_Status { get; set; }
        public virtual DbSet<Job_task> Job_task { get; set; }
        public virtual DbSet<Job_Task_Status> Job_Task_Status { get; set; }
        public virtual DbSet<Job_Task_Type> Job_Task_Type { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_Line> Order_Line { get; set; }
        public virtual DbSet<Order_Payment> Order_Payment { get; set; }
        public virtual DbSet<Order_Payment_Status> Order_Payment_Status { get; set; }
        public virtual DbSet<Order_Status> Order_Status { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Category> Product_Category { get; set; }
        public virtual DbSet<Product_Size> Product_Size { get; set; }
        public virtual DbSet<Product_Special> Product_Special { get; set; }
        public virtual DbSet<Product_Type> Product_Type { get; set; }
        public virtual DbSet<Quote_Line> Quote_Line { get; set; }
        public virtual DbSet<Quote_Status> Quote_Status { get; set; }
        public virtual DbSet<Raw_Material> Raw_Material { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Recipe_Line_Unit> Recipe_Line_Unit { get; set; }
        public virtual DbSet<Reciple_Line> Reciple_Line { get; set; }
        public virtual DbSet<Request_Quote> Request_Quote { get; set; }
        public virtual DbSet<Return_Order_Request> Return_Order_Request { get; set; }
        public virtual DbSet<Return_Order_Request_Order_Line> Return_Order_Request_Order_Line { get; set; }
        public virtual DbSet<Return_Sale_Request> Return_Sale_Request { get; set; }
        public virtual DbSet<Return_Sale_Request_Sale_Line> Return_Sale_Request_Sale_Line { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Sale_Line> Sale_Line { get; set; }
        public virtual DbSet<Sale_Payment> Sale_Payment { get; set; }
        public virtual DbSet<Sale_Payment_Status> Sale_Payment_Status { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Shift_Branch> Shift_Branch { get; set; }
        public virtual DbSet<Shift_Branch_Employee> Shift_Branch_Employee { get; set; }
        public virtual DbSet<Shift_Type> Shift_Type { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Special> Specials { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supplier_Order> Supplier_Order { get; set; }
        public virtual DbSet<Supplier_Order_Line> Supplier_Order_Line { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Time_Slot> Time_Slot { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Access_Permission> User_Access_Permission { get; set; }
        public virtual DbSet<VAT> VATs { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
        public virtual DbSet<Wishlist_Product> Wishlist_Product { get; set; }
    }
}
