//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Payment
    {
        public int Order_Payment_ID { get; set; }
        public int Order_Payment_Amount { get; set; }
        public System.DateTime Order_Payment_Date { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public Nullable<int> Order_Payment_Status_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Order_Payment_Status Order_Payment_Status { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
    }
}
