//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Special
    {
        public int Product_Special_ID { get; set; }
        public Nullable<int> Product_Size_ID { get; set; }
        public Nullable<int> Special_ID { get; set; }
        public float Price_Amount { get; set; }
    
        public virtual Product_Size Product_Size { get; set; }
        public virtual Special Special { get; set; }
    }
}
