//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_Line
    {
        public int Quote_Line_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Product_Size_ID { get; set; }
        public Nullable<int> Request_Quote_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product_Size Product_Size { get; set; }
        public virtual Request_Quote Request_Quote { get; set; }
    }
}
