//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reciple_Line
    {
        public int Reciple_Line_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Recipe_ID { get; set; }
        public Nullable<int> Raw_Material_ID { get; set; }
        public Nullable<int> Recipe_Line_unit_ID { get; set; }
    
        public virtual Raw_Material Raw_Material { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Recipe_Line_Unit Recipe_Line_Unit { get; set; }
    }
}
