//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Order_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Return_Order_Request()
        {
            this.Credit_Note = new HashSet<Credit_Note>();
            this.Return_Order_Request_Order_Line = new HashSet<Return_Order_Request_Order_Line>();
        }
    
        public int Return_Order_Request_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public System.DateTime Request_Order_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credit_Note> Credit_Note { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Order_Request_Order_Line> Return_Order_Request_Order_Line { get; set; }
    }
}
