//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Sale_Request_Sale_Line
    {
        public int Return_Sale_Request_Sale_Line_ID { get; set; }
        public string Return_Sale_Reason { get; set; }
        public Nullable<int> Return_Sale_Request_ID { get; set; }
        public Nullable<int> Sale_Line_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Return_Sale_Request Return_Sale_Request { get; set; }
        public virtual Sale_Line Sale_Line { get; set; }
    }
}
