//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Payment
    {
        public int Sale_Payment_ID { get; set; }
        public double Sale_Payment_Amount { get; set; }
        public System.DateTime Sale_Payment_Date { get; set; }
        public Nullable<int> Sale_Payment_Status_ID { get; set; }
        public Nullable<int> Sale_ID { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public Nullable<int> Register_ID { get; set; }
    
        public virtual Cash_Register Cash_Register { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Sale_Payment_Status Sale_Payment_Status { get; set; }
    }
}
