//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale_Line()
        {
            this.Return_Sale_Request_Sale_Line = new HashSet<Return_Sale_Request_Sale_Line>();
        }
    
        public int Sale_Line_ID { get; set; }
        public Nullable<int> Sale_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Sale_Request_Sale_Line> Return_Sale_Request_Sale_Line { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
