//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_Branch_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift_Branch_Employee()
        {
            this.Job_Instance = new HashSet<Job_Instance>();
        }
    
        public int Shift_Branch_Employee_ID { get; set; }
        public Nullable<int> Shift_Branch_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Instance> Job_Instance { get; set; }
        public virtual Shift_Branch Shift_Branch { get; set; }
    }
}
