//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift_Branch()
        {
            this.Shift_Branch_Employee = new HashSet<Shift_Branch_Employee>();
        }
    
        public int Shift_Branch_ID { get; set; }
        public Nullable<int> Shift_ID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift_Branch_Employee> Shift_Branch_Employee { get; set; }
    }
}
