//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order_Line
    {
        public int Supplier_Order_Line_ID { get; set; }
        public Nullable<int> Supplier_Order_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Raw_Material_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Raw_Material Raw_Material { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
