//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OVS_Team_3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist_Product
    {
        public int Wishlist_Product_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Wishlist_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Wishlist Wishlist { get; set; }
    }
}
